name: Create release
run-name: ${{ format('Create {0} release', inputs.version_type) }}

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version type'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  publish:
    name: Publish release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Exit early if not on 1.x
        if: github.ref != 'refs/heads/1.x'
        run: exit 1

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.NIGHTWATCH_PERMISSIONS_APP_ID }}
          private-key: ${{ secrets.NIGHTWATCH_PERMISSIONS_APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Bump version
        id: bump-version
        run: |
          VERSION_TYPE=${{ github.event.inputs.version_type }}

          if [[ "${VERSION_TYPE}" == "major" ]]; then
            INDEX=0
          elif [[ "${VERSION_TYPE}" == "minor" ]]; then
            INDEX=1
          elif [[ "${VERSION_TYPE}" == "patch" ]]; then
            INDEX=2
          else
            echo "Unknown version type [${VERSION_TYPE}]"
            exit 1
          fi

          IFS="."
          read -ra VERSION <<< $(<version.txt)

          echo "Bumping ${VERSION_TYPE} version"
          echo "Was: ${VERSION[0]}.${VERSION[1]}.${VERSION[2]}"

          VERSION[$INDEX]=$((VERSION[$INDEX] + 1))
          VERSION="${VERSION[0]}.${VERSION[1]}.${VERSION[2]}"

          echo "Now: ${VERSION}"
          echo "${VERSION}" > version.txt
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"

      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Bump version to v${{ steps.bump-version.outputs.version }}"
          tag: "v${{ steps.bump-version.outputs.version }}"
          push: true

      - uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          make_latest: true
          name: "v${{ steps.bump-version.outputs.version }}"
          tag_name: "v${{ steps.bump-version.outputs.version }}"
